#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sun Jul  7 21:28:06 2013

import wx
from math import sqrt

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Input your function")
        self.label_2 = wx.StaticText(self, -1, "x^2")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.label_3 = wx.StaticText(self, -1, "x^1")
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "x^0")
        self.text_ctrl_3 = wx.TextCtrl(self, -1, "")
        self.button_1 = wx.Button(self, -1, "Parse")
        self.label_5 = wx.StaticText(self, -1, "Roots")
        self.label_6 = wx.StaticText(self, -1, "Root 1")
        self.text_ctrl_4 = wx.TextCtrl(self, -1, "")
        self.label_7 = wx.StaticText(self, -1, "Root 2")
        self.text_ctrl_5 = wx.TextCtrl(self, -1, "")
        self.panel_5 = wx.Panel(self, -1)
        self.panel_1 = wx.Panel(self, -1)
        self.panel_2 = wx.Panel(self, -1)
        self.panel_3 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.parse, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("quadratic.py")
        self.SetSize((600, 300))
        self.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.label_1.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.label_2.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.label_3.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.label_4.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.label_5.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.label_6.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.text_ctrl_4.Enable(False)
        self.label_7.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.text_ctrl_5.Enable(False)
        self.panel_5.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.panel_1.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.panel_2.SetBackgroundColour(wx.Colour(234, 234, 234))
        self.panel_3.SetBackgroundColour(wx.Colour(234, 234, 234))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        grid_sizer_1 = wx.GridSizer(2, 3, 0, 0)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.label_2, 0, wx.LEFT, 2)
        sizer_2.Add(self.text_ctrl_1, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_3.Add(self.label_3, 0, wx.LEFT, 2)
        sizer_3.Add(self.text_ctrl_2, 0, 0, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.label_4, 0, wx.LEFT, 2)
        sizer_4.Add(self.text_ctrl_3, 0, 0, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(sizer_1, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_5, 0, wx.ALIGN_CENTER_HORIZONTAL, 1)
        sizer_6.Add(self.label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.text_ctrl_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_5, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetSizer(grid_sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def parse(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `parse' not implemented"

        a=self.text_ctrl_1.GetValue()
        b=self.text_ctrl_2.GetValue()
        c=self.text_ctrl_3.GetValue()
        a_2 = float(a)
        b_2 = float(b)
        c_2 = float(c)


        print a_2

        delta = b_2 * b_2 - 4 * a_2 * c_2
        if delta < 0:
            self.text_ctrl_4.SetValue("None")
            self.text_ctrl_5.SetValue("None")
        else:

            discroot = sqrt(delta)
            root1 = (-b_2 + discroot)/2
            root2 = (-b_2 - discroot)/2

            print root1
            print root2

            self.text_ctrl_4.SetValue(str(root1))
            self.text_ctrl_5.SetValue(str(root2))            
        print delta
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
